server:
  port: 8088

spring:
  datasource:
    name:
    url: jdbc:mysql://158.222.187.109:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml


