server:
  port: 8088

spring:
  datasource:
    name:
    url: jdbc:mysql://192.168.37.111:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: huayang

mybatis:
  mapper-locations: classpath:mapper/*.xml